### ISSUE TITLE
It's looking for config file in _Data/Managed folder

### ISSUE THREAD

**Issue by MaxCross2500** [DanielLavrushin/SaubNauticaBZ_QuickSlotsMod#1]
Mod doesn't seems to use any changes from config file. I tried too look to the source code, and, apparently, it's looking for config files in the `modInfoPath`, witch is resolved in `GetModInfoPath()` as `Environment.CurrentDirectory + "/" + modDirectory + "/mod.json"`, where `modDirectory` is set in `Load()` function to... `modDirectory ?? "SubnauticaZero_Data/Managed"`...
And yeah, if I just copy my config file to SubnauticaZero_Data/Managed folder, it's forks just fine, but i'm guessing Managed folder it's not where it should look for config file...
P.S Sorry if my english is too bad.

**Comment by DanielLavrushin** [comment]
should be fixed in the v1.6 :) thanks for reporting
